#!/bin/bash

BASEDIR="$(cd "$(dirname "$0")" && pwd)/../.."
RESULT="$BASEDIR/result"

TARGET_BL1_NAME=nxp3220

TARGET_BL2_CHIP=nxp3220
TARGET_BL2_BOARD=vtk
TARGET_BL2_PMIC=nxe1500
TARGET_BL2_NSIH=nsih_vtk_ddr3_800Mhz

TARGET_BL32_LOADADDRESS=0x5F000000
TARGET_BL32_LAUNCHADDRESS=0x5F000000

TARGET_KERNEL_DEFCONFIG=nxp3220_vtk_nand_defconfig
TARGET_KERNEL_DTB=nxp3220-vtk-nand

TARGET_UBOOT_DEFCONFIG=nxp3220_vtk_nand_defconfig

TARGET_BR2_DEFCONFIG=nxp3220_sysv_defconfig

# nand info
FLASH_PAGE_SIZE=2048
FLASH_BLOCK_SIZE=128K
FLASH_DEVICE_SIZE=256M

[[ $FLASH_PAGE_SIZE -gt 512 ]] && PSIZE=1024 || PSIZE=512

UBI_BOOTIMG_ARGS="-r ${RESULT}/boot -v boot -i 0 -l 32M -p $FLASH_PAGE_SIZE -b $FLASH_BLOCK_SIZE -c $FLASH_DEVICE_SIZE"
UBI_ROOTIMG_ARGS="-r ${RESULT}/rootfs -v rootfs -i 1 -l 59M -p $FLASH_PAGE_SIZE -b $FLASH_BLOCK_SIZE -c $FLASH_DEVICE_SIZE"

CONFIGDIR="$(cd "$(dirname "$0")" && pwd)"/configs

source $CONFIGDIR/build.common-nand.sh
